#!/usr/bin/env bash

#sudo apt-get install curl

if [ -z ${XDG_CONFIG_HOME+x} ]; then
	XDG_CONFIG_HOME="~/.config"
fi

# setup fzf
if ! test -x $(which fzf); then
	git clone --depth 1 https://github.com/junegunn/fzf.git ~/.config/fzf
	~/.config/fzf/install --all --xdg --no-bash --no-zsh
fi

# add ppas
#PPA_FISH="fish-shell/release-3"

#if ! grep -q "^deb .*${PPA_FISH}" /etc/apt/sources.list /etc/apt/sources.list.d/*; then
#	sudo apt-add-repository "ppa:fish-shell/release-3"
#fi

#sudo apt-get update
#sudo apt-get install -y fish

# python
sudo apt install python3-pip
pip install --user virutalfish

# fish path
fish -c 'fish_add_path "~/.local/bin"'

# virtual fish
fish -c 'vf install projects auto_activation  global_requirements environment'
fish -c 'exec fish'

# fish
if test -x $(which fish); then
	#chsh -s "$(which fish)" $USER
	curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
	fish -c "fisher install jethrokuan/fzf"
	fish -c "fisher install jethrokuan/z"
	fish -c "fisher install laughedelic/pisces"
fi


# node
sudo curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
sudo echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt update
sudo apt install yarn




# vim: ft=sh
